---
abstract: 'preview tickets right from search results page'
author:
  - 'Ruslan Zakirov <ruz@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-PreviewInSearch
no_index:
  directory:
    - html
    - inc
requires:
  perl: 5.10.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
